version: '3.9'
services:

  nginx:
    container_name: nxinx-router
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    restart: unless-stopped
    ports:
      - "80"    # http
      - "443:443"   # https
    volumes:
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
#      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx

