version: '3.9'
services:

  memcached:
    image: amd64/memcached:1.6

  database:
    # default port 3306
    image: mariadb:10.11
    restart: unless-stopped
    networks:
      - wordpress
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'

  wordpress:
    # default port 9000 (FastCGI)
    build: docker/wordpress/
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - database
      - memcached
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
      # - /path/to/repo/myTheme/:/var/www/html/wp-content/themes/myTheme
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1
    restart: unless-stopped
    networks:
      - wordpress
    depends_on:
      - wordpress
      - memcached
    ports:
      - "${NGINX_HTTP_PORT}"    # http
      - "${NGINX_HTTPS_PORT}:443"   # https
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx

  # adminer - bring up only as needed - bypasses nginx
#  adminer:
#    # default port 8080
#    image: adminer:4
#    container_name: wp-adminer
#    restart: unless-stopped
#    networks:
#      - wordpress
#    depends_on:
#      - database
#    ports:
#      - "9000:8080"

networks:
    wordpress:
       name: ${WORDPRESS_NETWORK}
       driver: bridge